name: conda_env
channels:
  - conda-forge
  - defaults

dependencies:
  - affine=2.4.0
  - aiodns=3.5.0
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.12.15
  - aiosignal=1.4.0
  - amqp=5.3.1
  - anywidget=0.9.18
  - aom=3.9.1
  - asgiref=3.10.0
  - asttokens=3.0.0
  - async-timeout=5.0.1
  - attrs=25.4.0
  - backports.zoneinfo=0.2.1
  - beautifulsoup4=4.14.2
  - billiard=4.2.1
  - binutils_impl_win-64=2.44
  - blosc=1.21.6
  - bqplot=0.12.45
  - branca=0.8.2
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - brotli=1.1.0
  - bwidget=1.10.1
  - bzip2=1.0.8
  - c-ares=1.34.5
  - cachetools=5.5.1
  - cairo=1.18.4
  - celery=5.5.3
  - certifi=2025.11.12
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - click-didyoumean=0.3.1
  - click-plugins=1.1.1.2
  - click-repl=0.2.0
  - click=8.3.0
  - cligj=0.7.2
  - colorama=0.4.6
  - colour=0.1.5
  - comm=0.2.3
  - contourpy=1.3.2
  - coverage=7.11.0
  - cron-descriptor=1.4.5
  - cryptography=44.0.1
  - curl=8.14.1
  - cycler=0.12.1
  - dav1d=1.2.1
  - decorator=5.2.1
  - django-celery-beat=2.8.1
  - django-cors-headers=4.9.0
  - django-crontab=0.7.1
  - django-extensions=4.1
  - django-storages=1.14.6
  - django-timezone-field=7.1
  - django=5.2.7
  - djangorestframework=3.16.1
  - earthengine-api=1.6.13
  - eerepr=0.1.2
  - exceptiongroup=1.3.0
  - executing=2.2.1
  - ffmpeg-python=0.2.0
  - ffmpeg=8.0.0
  - filelock=3.20.0
  - fiona=1.10.1
  - folium=0.20.0
  - fontconfig=2.15.0
  - fonttools=4.60.1
  - freetype=2.14.1
  - freexl=2.0.0
  - fribidi=1.0.16
  - frozenlist=1.8.0
  - future=1.0.0
  - gcc_impl_win-64=15.2.0
  - gdal=3.10.3
  - gdk-pixbuf=2.44.4
  - gdown=5.2.0
  - geeadd=0.5.6
  - geemap=0.36.6
  - geocoder=1.38.1
  - geodatasets=2024.8.0
  - geojson=3.2.0
  - geopandas-base=1.1.1
  - geopandas=1.1.1
  - geos=3.14.0
  - geotiff=1.7.4
  - gfortran_impl_win-64=15.2.0
  - glslang=16.0.0
  - google-api-core=2.26.0
  - google-api-python-client=2.185.0
  - google-auth-httplib2=0.2.0
  - google-auth=2.38.0
  - google-cloud-core=2.4.3
  - google-cloud-storage=3.4.1
  - google-crc32c=1.6.0
  - google-resumable-media=2.7.2
  - googleapis-common-protos=1.69.2
  - graphite2=1.3.14
  - gsl=2.7
  - gxx_impl_win-64=15.2.0
  - h2=4.3.0
  - harfbuzz=12.1.0
  - hpack=4.1.0
  - httplib2=0.31.0
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.11
  - imageio=2.37.0
  - importlib-metadata=8.5.0
  - iniconfig=2.1.0
  - ipyevents=2.0.4
  - ipyfilechooser=0.6.0
  - ipyleaflet=0.20.0
  - ipython=8.37.0
  - ipytree=0.2.2
  - ipywidgets=8.1.7
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.5.2
  - jupyter_leaflet=0.20.0
  - jupyterlab_widgets=3.0.15
  - kiwisolver=1.4.9
  - kombu=5.5.4
  - krb5=1.21.3
  - lame=3.100
  - lazy-loader=0.4
  - lcms2=2.17
  - ld_impl_win-64=2.44
  - lerc=4.0.0
  - llvm-openmp=21.1.3
  - llvmlite=0.45.1
  - logzero=1.7.0
  - lz4-c=1.10.0
  - lzo=2.10
  - m2-conda-epoch=20250515
  - mapclassify=2.8.1
  - markupsafe=3.0.3
  - matplotlib-base=3.10.7
  - matplotlib-inline=0.1.7
  - minizip=4.0.10
  - mkl=2024.2.2
  - multidict=6.7.0
  - munkres=1.1.4
  - narwhals=2.9.0
  - networkx=3.4.2
  - numba=0.62.1
  - numpy=2.2.6
  - openh264=2.6.0
  - openjpeg=2.5.4
  - openssl=3.6.0
  - packaging=25.0
  - pandas=2.3.3
  - pango=1.56.4
  - parso=0.8.5
  - pcre2=10.46
  - pickleshare=0.7.5
  - pillow=11.3.0
  - pip=25.2
  - pixman=0.46.4
  - platformdirs=4.5.0
  - plotly=6.3.1
  - pluggy=1.6.0
  - pooch=1.8.2
  - proj=9.6.2
  - prompt-toolkit=3.0.52
  - prompt_toolkit=3.0.52
  - propcache=0.3.1
  - proto-plus=1.26.1
  - protobuf=5.29.3
  - psygnal=0.14.2
  - pthread-stubs=0.4
  - pure_eval=0.2.3
  - pyasn1-modules=0.4.2
  - pyasn1=0.6.1
  - pycares=4.10.0
  - pycparser=2.22
  - pycrs=1.0.2
  - pygments=2.19.2
  - pyogrio=0.11.0
  - pyopenssl=25.0.0
  - pyparsing=3.2.5
  - pyperclip=1.11.0
  - pyproj=3.7.1
  - pyshp=3.0.2
  - pysocks=1.7.1
  - pytest-cov=7.0.0
  - pytest=8.4.2
  - python-box=7.3.2
  - python-crontab=3.3.0
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.2
  - python=3.10.19
  - python_abi=3.10
  - pytz=2025.2
  - pywavelets=1.8.0
  - pyyaml=6.0.3
  - qhull=2020.2
  - r-base=4.4.3
  - r-filelock=1.0.3
  - rasterio=1.4.3
  - ratelim=0.1.6
  - requests=2.32.5
  - rpy2-rinterface=3.6.2
  - rpy2-robjects=3.6.1
  - rpy2=3.6.2
  - rsa=4.7.2
  - ruamel.yaml.clib=0.2.14
  - ruamel.yaml=0.18.16
  - schedule=1.2.2
  - scikit-image=0.25.2
  - scikit-learn=1.7.2
  - scipy=1.15.2
  - scooby=0.10.2
  - sdl2=2.32.56
  - sdl3=3.2.24
  - setuptools=80.9.0
  - shaderc=2025.4
  - shapely=2.1.2
  - six=1.17.0
  - snappy=1.2.2
  - snuggs=1.4.7
  - soupsieve=2.8
  - spirv-tools=2025.4
  - sqlite=3.50.4
  - sqlparse=0.5.3
  - stack_data=0.6.3
  - svt-av1=3.1.2
  - tbb=2021.13.0
  - threadpoolctl=3.6.0
  - tifffile=2025.2.18
  - tk=8.6.13
  - tktable=2.10
  - toml=0.10.2
  - tomli=2.3.0
  - tqdm=4.67.1
  - traitlets=5.14.3
  - traittypes=0.2.3
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - tzdata=2025b
  - tzlocal=5.3.1
  - unicodedata2=16.0.0
  - uriparser=0.9.8
  - uritemplate=4.2.0
  - urllib3=2.5.0
  - vine=5.1.0
  - watchdog=6.0.0
  - wcwidth=0.2.14
  - wheel=0.45.1
  - widgetsnbextension=4.0.14
  - win_inet_pton=1.1.0
  - winloop=0.2.2
  - wrapt=2.0.0
  - x264=1!164.3095
  - x265=3.5
  - xerces-c=3.2.5
  - xyzservices=2025.4.0
  - yaml=0.2.5
  - yarl=1.18.0
  - zipp=3.21.0
  - zlib=1.3.1
  - zstandard=0.25.0
  - zstd=1.5.7
